services:
  logchecker:
    image: ghcr.io/nirzak/audio-ripping-logchecker:test
    container_name: logchecker
    environment:
      - PUID=1002
      - PGID=1002
      - SUBPATH=/logchecker
      - LOG_LEVEL=info
      - RATE_LIMIT=1000 per minute
    ports:
      - "5050:5050"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
