services:
  logchecker-test:
    image: ghcr.io/nirzak/eac-xld-logchecker-web:test
    container_name: logchecker-test
    build: .
    environment:
      - PUID=1002
      - PGID=1002
      - SUBPATH=/logchecker
      - LOG_LEVEL=error
    ports:
      - "5051:5050"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
